import type { NextPage } from "next"
import Head from "next/head"
import HomeSection from "../components/sections/Home/HomeMainSection"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="theme-color" content="#A7A7A7" />
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeSection />
      </main>
    </>
  )
}

export default Home